Ensure address is correct
zincware/ZnDraw pull request #588
Opened 2024-08-03 14:33 UTC by phohenberger

Tokens containing `ws` were getting also replaced. This only replaces the protocol.

2024-08-04 18:15 UTC, PythonFZ requested changes
Can you move the function to utils, add a test case with / without `ws` in the token and also use it https://github.com/zincware/ZnDraw/blob/cb3631d5eda77a9e2264cdddba974bf08e2bd301/zndraw/zndraw.py#L85

2024-08-04 18:15 UTC, PythonFZ commented on zndraw/zndraw.py
> +        address = parsed_url._replace(scheme="http").geturl()
Is there a way to rename the schema without using the "private" `_replace` method?

2024-08-07 20:11 UTC, PythonFZ commented
I have added a test for https (maybe try it with the hosted zndraw). I think this should be fixed.

2024-08-07 20:21 UTC, phohenberger commented
The previous replacement was also only for `http`. The function would have to know what protocol it should be using, based on the previous code I just assumed it would be `http`. I do not know when it should have to `https` or `http`

2024-08-07 20:26 UTC, PythonFZ commented
> The previous replacement was also only for `http`. The function would have to know what protocol it should be using, based on the previous code I just assumed it would be `http`. I do not know when it should have to `https` or `http`

When the adress is given as `https` it should be `wss` and if given as `http` the protocol is `ws`. The `replace` cmd has worked for both, because it only replaced the first part of `http_s_` with `ws`. If you say it is not required when using e.g.

```python
from zndraw import ZnDraw

vis = ZnDraw(url="https://zndraw.icp.uni-stuttgart.de", token="erik_e")
```

We can remove the tests but I'd assume it needs the correct protocol?

2024-08-07 20:28 UTC, phohenberger commented
Ah, alright. No, i can just filter the previous `scheme` and use `https` for `wss` and ``http` for `ws`. This should work

2024-08-07 20:44 UTC, PythonFZ approved these changes

2024-08-07 20:48 UTC, merged